image: node:18.17.1

stages:
  - build

variables:
  NODE_ENV: "development"

before_script:
  - cd back
  - npm install

lint:
  stage: build
  script:
    - npm run lint
  only:
    changes:
      - "back/**/*"

test:
  stage: build
  script:
    - npm run lint
  only:
    changes:
      - "back/**/*"
